services:
  selenoid:
    image: aerokube/selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - ../config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/video:/opt/selenoid/video
      - ./selenoid/logs:/opt/selenoid/logs
    command:
      [
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-log-output-dir", "/opt/selenoid/logs",
        "-timeout", "60s"
      ]

  selenoid-ui:
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  teamcity-server:
    image: jetbrains/teamcity-server:latest
    network_mode: bridge
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity_server/data:/data/teamcity_server/datadir
      - ./teamcity_server/logs:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    network_mode: bridge
    links:
      - teamcity-server
    environment:
      - SERVER_URL=http://teamcity-server:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./teamcity_agent/conf:/data/teamcity_agent/conf
